set(MIDDLEWARE_SOURCES_FILES
   "Src/led.c"
)

add_library(${MIDDLEWARE_LIBRARY_TARGET} STATIC
   ${MIDDLEWARE_SOURCES_FILES}
)

target_include_directories( ${MIDDLEWARE_LIBRARY_TARGET} PUBLIC
   "${CMAKE_CURRENT_SOURCE_DIR}/.."
)

target_compile_options( ${MIDDLEWARE_LIBRARY_TARGET} PRIVATE
   ${LIBRARY_WARNING_FLAGS}
   ${LIBRARY_ASSERT_FLAGS}
)