# https://github.com/danmar/cppcheck
name: Cppcheck

on: [push]

jobs:
  cppcheck:
    name: Cppcheck

    runs-on: ubuntu-latest
    container:
      image: charlesdias/stm32_gtest:latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Cppcheck scan with the MISRA C:2012 addon
        run: make cppcheck

      - name: Upload analysis results
        uses: actions/upload-artifact@v7
        with:
          name: cppcheck-report
          path: build/cppcheck-report.txt
          retention-days: 90
