name: Test

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: charlesdias/stm32_gtest:latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure, build, and run Google Test
      run: |
        make test

    - name: Run coverage
      run: |
        make coverage

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        gcov_ignore: 
          ./build
          ./docs
          ./tests