name: Test

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: charlesdias/gcc-arm-cmake:latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure and build
      run: |
        make build

    - name: Run Google Test
      run: |
        make test

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        gcov_ignore: 
          ./build
          ./docs
          ./tests